/**
 * Copies MapLibre's web-worker bundle into `public/` so it can be served
 * as a static asset.
 *
 * Why this is needed: maplibre-gl v6 spawns its worker with
 * `new Worker(new URL("./maplibre-gl-worker.mjs", import.meta.url), {type:"module"})`.
 * Next.js/Turbopack rewrites the importing module's URL during bundling, so
 * that relative resolution lands somewhere that does not exist, and the map
 * dies with "Worker failed to load. Check that the worker URL is correct."
 * on a blank canvas. Serving the worker from a fixed public path and
 * pointing `setWorkerUrl` at it sidesteps bundler URL rewriting entirely.
 *
 * Both files are required and must stay siblings: the worker does
 * `import ... from "./maplibre-gl-shared.mjs"`, which resolves relative to
 * wherever the worker is served from.
 *
 * Run automatically via the `prepare-assets` npm script (wired into `dev`
 * and `build`) rather than committed, so the copies can never drift out of
 * sync with the installed maplibre-gl version.
 */
import { copyFileSync, mkdirSync, existsSync, readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const here = path.dirname(fileURLToPath(import.meta.url));
const root = path.join(here, "..");
const srcDir = path.join(root, "node_modules", "maplibre-gl", "dist");
const outDir = path.join(root, "public", "maplibre");

const FILES = ["maplibre-gl-worker.mjs", "maplibre-gl-shared.mjs"];

function main() {
  if (!existsSync(srcDir)) {
    process.stderr.write(
      `maplibre-gl is not installed (${srcDir} missing). Run npm install first.\n`
    );
    process.exit(1);
  }

  mkdirSync(outDir, { recursive: true });
  for (const f of FILES) {
    const from = path.join(srcDir, f);
    if (!existsSync(from)) {
      process.stderr.write(
        `Expected ${f} in maplibre-gl/dist but it is missing. The package layout may have ` +
          `changed in this version - check how the worker is bundled before upgrading.\n`
      );
      process.exit(1);
    }
    copyFileSync(from, path.join(outDir, f));
  }

  // Record the version the copies came from, so a mismatch after an upgrade
  // is visible rather than silently serving a stale worker.
  const pkg = JSON.parse(
    readFileSync(path.join(root, "node_modules", "maplibre-gl", "package.json"), "utf8")
  );
  writeFileSync(
    path.join(outDir, "VERSION"),
    `${pkg.version}\ngenerated by scripts/copyMaplibreWorker.mjs - do not edit\n`
  );

  process.stdout.write(`Copied maplibre-gl worker v${pkg.version} to public/maplibre/\n`);
}

main();
